name: MSBuild

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  # Correct path from repo root to your solution:
  SOLUTION_FILE_PATH: Prog4Ass1/Minigin.sln

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        BUILD_CONFIGURATION: [Debug, Release]
        BUILD_PLATFORM:    [Win32, x64]

    steps:
      - uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Restore NuGet packages
        # will do nothing now if you have no packages, but safe to leave:
        run: nuget restore ${{ env.SOLUTION_FILE_PATH }}

      - name: Build solution
        run: msbuild ${{ env.SOLUTION_FILE_PATH }} \
              /m \
              /p:Configuration=${{ matrix.BUILD_CONFIGURATION }} \
              /p:Platform=${{ matrix.BUILD_PLATFORM }}
