name: MSBuild CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # ← point to the real .sln
  SOLUTION_FILE_PATH: Prog4Ass1/Minigin.sln

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        BUILD_CONFIGURATION: [Debug, Release]
        BUILD_PLATFORM:    [Win32, x64]

    steps:
      - uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Build solution
        run: msbuild ${{ env.SOLUTION_FILE_PATH }} /restore /m \
             /p:Configuration=${{ matrix.BUILD_CONFIGURATION }} \
             /p:Platform=${{ matrix.BUILD_PLATFORM }}
